### ISSUE TITLE
Typos in the require section

### ISSUE THREAD

**Issue by giladyavneh** [suvelocity/challenge-sequelize-template#2]
The first line requires mySequlize from "mySequlize", while the file name is "index".
The third line requires Op from "OpsSymbols", while the file name is "OpSymbols" (notice the missing **s**)
Nice chalenge though!

https://github.com/suvelocity/challenge-sequelize-template/blob/07308c87f3866fdf3f4c93be16fd213f04233852/test.test.js#L1-L3

**Comment by OfirSimhi1612** [comment]
fixed
